server:
  port: 8100
spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ZZhpzhrGZ8PaD3iG
    url: jdbc:mysql://47.96.236.125:3306/blogs
    username: blogs
  redis:
    host: 47.96.236.125
    port: 6379
    password: gaoyifeng
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2244952274@qq.com
    #授权码
    password: dpotbizabinwdiih
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    port: 465